require: 
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'Rakefile'
    - 'config.ru'

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false


Style/FrozenStringLiteralComment:
  Enabled: false
